version: 2
models:
  - name: fct_reviews
    columns:
      - name: listing_id
        tests:
          - relationships:
              to: ref('dim_listings_cleansed')
              field: listing_id
      - name: reviewer_name
        tests:
          - not_null
      - name: review_sentiment
        tests:
          - accepted_values:
              values:
                - positive
                - neutral
                - negative