version: 2

sources:
  - name: sandbox
    schema: airbnb_raw
    tables:
      - name: listings
        identifier: raw_listings
        freshness:
          warn_after: 
            count: 25
            period: day
          error_after: 
            count: 30 
            period: day
        loaded_at_field: UPDATED_AT                 
        columns:
          - name: room_type
            tests:
              - dbt_expectations.expect_column_distinct_count_to_equal:
                  value: 4
          - name: price
            tests:
              - dbt_expectations.expect_column_values_to_match_regex:
                  regex: "^\\\\$[0-9][0-9\\\\.]+$"
      - name: hosts
        identifier: raw_hosts

      - name: reviews
        identifier: raw_reviews
        freshness: null
